### ISSUE TITLE
Handgun and Mega Man content

### ISSUE THREAD

**Issue by DWN009** [dgk3593/dl-model#3]
The handgun's "glock_slide_low" in the extra weapons has a giant duplicate.

And can I request the inclusion of the following Mega Man content?
*Mega Man's Metal Blade and Leaf Shield pallettes for his textures.
*A Dr. Wily model separated from his Wily Machine.
*The five brainwashed dragons (or at least their eyes for their normal versions if that's the only difference).
*Mega Man's Mega Buster for extra weapons.

**Comment by dgk3593** [comment]
- The gun duplicate was a relic of the time when it wasn't possible to scale weapon size but atm, it's because having only 1 weapon in the extra section looks sad xD
- Mega Man textures added
- You can have Wily model by hiding the machine parts for now, since he has a different skeleton from adv, he won't be able to use their animations so it's not worth the time to create that model
- There doesn't seem to be any files specific to the brainwashed dragons in the assets
- For Mega Buster, making it an extra weapon will attach it to jWeaponR or jWeaponL and those won't look right, for now try adding Mega Man to jHandR, hide Face and mBodyAll, move position to x = -0.29, y = -0.425, and change rotation to z = -0.15

**Comment by DWN009** [comment]
1 - Well, the extras could also hold props to increase its size, like an Eldwater for the Eldwater animation, a cup for the Sit and Drink animation, ... Or, like the backgrounds and animations, an option to upload custom objects?
2 - Thanks!

4 - Not even with a full asset download? Then I suppose their assets were removed after the event ended...

**Comment by dgk3593** [comment]
For the cup, I'm planning to add a 5th Object category
Mega man texture is actually changed with a shader in the game so I think the dragons are too
